### ISSUE TITLE
Barebones C# project -- Fody: Could not find a weaver named 'NullGuard'

### ISSUE THREAD

**Issue by tricus** [Fody/NullGuard#100]
After updating to latest Fody 2.4.1 & NullGuard 1.7.0, Fody can't find NullGuard.
Worked fine with Fody 2.2.0 & NullGuard 1.6.2.

Minimal VS20170 solution exhibiting the error:  [Fody.NullGuard.Test.zip](https://github.com/Fody/NullGuard/files/1728633/Fody.NullGuard.Test.zip)

**Comment by SimonCropp** [comment]
Is the entry missing from the fodyweavers.xml?

**Comment by tricus** [comment]
No, it's there:
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <NullGuard />
</Weavers>

**Comment by anuviswan** [comment]
Hi, I ran into same issue. Combination was same Fody 2.4.1 and NullGuard 1.7.0.

**Comment by SimonCropp** [comment]
I am on holidays. If someone wants to fix this and send me a PR i can do a release

**Comment by SimonCropp** [comment]
Can u try 1.7.1
