### ISSUE TITLE
Inconclusive/aborted tests when passing NULL to guarded method

### ISSUE THREAD

**Issue by Remedij** [Fody/NullGuard#101]
When trying to run a failing test (pass null) on some class/method, which is nullguarded, tests will hang out. 

ClassLibrary1 has NullGuard nuget, contains a class with simple method: 
`public string TestMethod(string input)
        {
            return input;
        }`

UnitTestProject has reference to ClassLibrary project and contains two simple tests:

- passing test: `new Class1().TestMethod("sadfa");`
- failing test: `new Class1().TestMethod(null);`

First test runs fine, but the failing one hangs out. In log, there is no exact reason: 
"The active test run was aborted. Reason: Test.TestAdapter.Execution.TestMethodRunner.Execute()
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunSingleTest(Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.TestMethod, System.Collections.Generic.IDictionary`2<System.String,System.Object>)"

ClassLibrary1 is .NetStandard2.0 class library + NullGuard.Fody 1.7.1 + Fody 2.4.1
UnitTestProject is ..NET Core 2.0 test project

I tried both MS Test and xUnit tests, both VS test explorer and Resharper test explorer. Same result every time.

When i remove NullGuard.Fody package, tests behave as expected.

SourceCode:
[UnitTestProject.zip](https://github.com/Fody/NullGuard/files/1793751/UnitTestProject.zip)

**Comment by Remedij** [comment]
My bad, forget it :)

**Comment by JohnTheGray** [comment]
Just in case anyone is wondering what the problem is: for debug builds NullGuard weaves `Debug.Assert` instead throwing the `ArgumentNullException`. Try configure with:

`<NullGuard IncludeDebugAssert="false" />`
