### ISSUE TITLE
ExcludeRegex doesn't work with inheritance

### ISSUE THREAD

**Issue by hasanmanzak** [Fody/NullGuard#104]
ExcludeRegex configuration doesn't process on class inheritance. It just checks current type's fullname. Shouldn't it be checking base classes, too?

Offending line is in `ModuleWeaver.GetTypesToProcess` method:

`return allTypes.Where(x => !ExcludeRegex.IsMatch(x.FullName)).ToList();`

**Comment by SimonCropp** [comment]
see https://github.com/Fody/NullGuard/pull/105#issuecomment-386802098
