### ISSUE TITLE
Add support for null checks on internal members

### ISSUE THREAD

**Issue by DEVA9N** [Fody/NullGuard#188]
We'd like to use NullGuard to check arguments for public and internal methods. 

The ValidationFlags allow either to check public or non public methods - which would also introduce null checks to our private methods. We would like to offer our developers the freedom to chose how to implement private methods. That's why we don't want to enforce the null checks for private members.

An additional flag which allows to check internal methods would be appreciated. If there already is a way to limit the check to public and internal member please tell me how.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
