### ISSUE TITLE
Debug.Assert should be opt in

### ISSUE THREAD

**Issue by JakeGinnivan** [Fody/NullGuard#23]
I run debug builds locally, but with Debug.Assert nCrunch gets blocked by a window causing tests to hang.

This should be an opt in feature imo

**Comment by cwchapma** [comment]
I agree, this should be opt-in.  Just spent an hour trying to figure out why there were dialogs being thrown up when using LIve Unit Testing.  Catching and hiding ArgumentNullExceptions or any exception is a totally different problem and shouldn't be attempted to be solved here IMO.

**Comment by SimonCropp** [comment]
I actually dont understand the reasoning behind using debug assert at all? why is that preferential over a arg exception? @distantcam

**Comment by SimonCropp** [comment]
@cwchapma  BTW to be using fody you should be a patron https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by distantcam** [comment]
@SimonCropp See issue #13 

Also debug asserts are only in the debug build. Release builds are unaffected.

**Comment by SimonCropp** [comment]
shouldnt the null guard be injected above the try?

**Comment by SimonCropp** [comment]
bump
