### ISSUE TITLE
Proposal: "UseDefaultNullArgumentMessage" option

### ISSUE THREAD

**Issue by mikernet** [Fody/NullGuard#260]
I would like to add an option called something like `UseDefaultNullArgumentMessage` or `UseSystemNullArgumentMessage` or similar that will cause the `ArgumentNullException` instances to be built using the constructor with just the parameter name and no message parameter.

Any opposition to that? I would like to throw that in with the NRT pull request I'm working on at the moment.

This will allow release builds to use the standard localized .NET exception messages instead of the English-only NullGuard message. It will also reduce assembly size a bit because it doesn't need to embed as many strings and emit as many opcodes for each check.

The normal behavior should also be changed so it does not write the name of the parameter into the message. All `ArgumentException` implementations automatically append the name of the parameter, which is causing it to show up twice in the message right now. Standard practice is to use a generic message such as `[NullGuard] Value cannot be null` which will cause the exception message to return `[NullGuard] Value cannot be null (Parameter: 'paramName')`.

**Comment by tom-englert** [comment]
@mikernet that sounds reasonable to me, we should not spent more resources than neccessary for a thing that should practially never happen.
I even wouldn't make this configurable...

**Comment by mikernet** [comment]
I'm actually done making it configurable, was about to commit and push the changes. I picked that route because there's a bajillion tests that will fail otherwise because they test the exception messages so it seemed easier just add the config switch. I can remove configurability if you want but then we are going to have to go and update all the .verify file contents and maaany tests would have to be substantially rewritten, i.e. the ones that attempt to verify that the existing guard clause checker is working correctly by testing which exception message shows up. I'm already done the config setting so it's up to you.

**Comment by mikernet** [comment]
I just have a simple boolean UseNullGuardNullArgumentMessage setting in the weaver xml config

**Comment by tom-englert** [comment]
Thats OK, just wondered why this was closed. 
Just make sure this goes into a separate PR, and the PR references this issue.

**Comment by mikernet** [comment]
So just to be clear, which route do you want me to take - configurable as it is now or non-configurable?

If you want to fix the double parameter name showing up in the exception message issue that I mentioned then we might as well just make it non-configurable and clean things up because changing the message format will change all the .verify file results anyway.

**Comment by mikernet** [comment]
Do you want me to PR this to our other repo NullReferenceTypes branch and merge there or PR directly to this repo? If we do separate PRs to this repo then won't it be rather annoying to keep the two branches in sync as we continue to work on this considering they will both have a ton of overlapping conflicts for the files they change?

**Comment by mikernet** [comment]
Nvm, I think I figured out how to do this in a sensible fashion. Let me know if I end up doing something that doesn't make sense :P

**Comment by mikernet** [comment]
Okay, no, sorry, still need clarification. Once I create a branch for this, which branch in which repo am I sending the PR to?

**Comment by mikernet** [comment]
Just slightly confused by the fact that our active repo is a different repo than this issue. I'm guessing you want me to PR to master here because there's no reason for me to PR within the repo that I'm a contributor in so I'll do that and you let me know if I messed something up.
