### ISSUE TITLE
Add property setter validations only

### ISSUE THREAD

**Issue by omeshechkov** [Fody/NullGuard#356]
Usually (in my practice) when you decide make your property not-nullable, you initialize it from constructor (where you have null-check for corresponding argument) and you do null-check only in setter. In such "configuration" null have no chances to get into the property.

It would be great to have ability to check property setters only. 
NullGuard already have `ValidationFlags.Property`. It would be nice to split it into two values `PropertySetter` and `PropertyGetter` and `ValidationFlags.Property` will consist both of them. I think it will be enough elegant way to solve this concern and save backward compatibility.

**Comment by SimonCropp** [comment]
can u re-read the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by omeshechkov** [comment]
I'm very sorry about I haven't read template((

I supposed my comment is a proposal, not an issue. So I've read https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/feature_proposal.md too. 
Do I need to be a Patron on OpenCollective in this case to create proposal?

**Comment by SimonCropp** [comment]
yes
