### ISSUE TITLE
Strong Signing

### ISSUE THREAD

**Issue by MovGP0** [Fody/NullGuard#47]
I get the following error when adding NullGuard to my project: 

    Assembly '...\NullGuard.Fody.1.2.0.0\Lib\portable-net4+sl4+wp7+win8+MonoAndroid16+MonoTouch40\NullGuard.dll' must be strong signed in order to be marked as a prerequisite.

I guess the assembly is not properly signed?

**Comment by MovGP0** [comment]
I solved it this way: http://stackoverflow.com/a/8123074/601990

**Comment by Haacked** [comment]
I'm trying to use NullGuard with a VS extension which has to be signed because, VS. Do I need to sign NullGuard myself? NullGuard writes itself out of the final assembly, right? So I would assume all the concerns about strong naming wouldn't apply, no?

**Comment by SimonCropp** [comment]
done in 1.4
