### ISSUE TITLE
Allow to configure IncludeDebugAssert with an assembly attribute

### ISSUE THREAD

**Issue by ulrichb** [Fody/NullGuard#48]
This would solve 2 issues:
- The `IncludeDebugAssert` flag cannot be configured "by code" and therefore is a asymmetric with the the `ValidationFlags` configuration which can be configured with the `[NullGuard]` (assembly) attribute.<br/>This is the reason, why our `NullGuard` configuration is scattered at the moment (a solution-wide `AssemblyInfo.cs` + a solution-wide `FodyWeavers.xml`).

- When having a solution-wide `FodyWeavers.xml` (including `<NullGuard IncludeDebugAssert="false" />`), the project-specific one gets overridden with `<NullGuard/>` on a package update and therefore overrides the `IncludeDebugAssert` value. So, the `<NullGuard/>` entry has to be deleted from the project-specific `FodyWeavers.xml` after every package update in our case.

Would you accept a PR?

**Comment by distantcam** [comment]
Yes I'd be happy to accept a PR for this.

**Comment by ulrichb** [comment]
Do you think there should also be an assembly attribute for `ExcludeRegex`? 

For us this is not a requirement at the moment, but theoretically there are also be use cases to configure this by code (e.g. a project containing NuGet source packages, where you don't want to change the included source files, but put an assembly attribute somewhere else in the project).

**Comment by distantcam** [comment]
No, excluderegex is doing something different. Let's leave it out for now.

**Comment by c0ntinuum** [comment]
> , the project-specific one gets overridden with <NullGuard/> on a package update and therefore overrides the IncludeDebugAssert value

Would you like a separate PR to fix this (it seems like a bug in then nuget to me) or will this get handled by this PR?

**Comment by distantcam** [comment]
@c0ntinuum I'm not sure this should be fixed. I think the current behaviour works, and solution level config is rarely used.

And even if it was to be fixed it would need to be fixed in the Fody project, not here.

**Comment by c0ntinuum** [comment]
> I think the current behaviour works.

It seems like a _smell_ to me that you upgrade `NullGuard.Fody` and it rewrites your `FodyWeavers.xml` removing `IncludeDebugAssert="false" which then has the knock on effect of changing the behaviour of your application post upgrade.

I would have thought a check for an existing `<NullGuard ? />` in `FodyWeavers.xml` on upgrade (and then don't override) would have been the way to go?

Bear in mind that I'm really new to _Fody_ and _Fody.NullGuard_ so I may have no concept of what I'm talking about...

**Comment by distantcam** [comment]
@c0ntinuum That's not what is happening.

Fody allows for a config at the solution level, and at the project level. The original problem is that the project level settings override the solution level ones, which I feel is the most appropriate behaviour.

**Comment by SimonCropp** [comment]
i think @distantcam has adequately answered this
