### ISSUE TITLE
ExcludeRegex should be able to match namespace

### ISSUE THREAD

**Issue by JakeGinnivan** [Fody/NullGuard#49]
I have some code NuGet packages which are not attributed with NullGuard attributes. Ideally I just want to `ExcludeRegex=App_Packages` and it works. But it seems that this property only supports the classname?

**Comment by distantcam** [comment]
Correct. Fody only works on the compiled code, so there's no way to tell which class came from which code file. So unless all the classes you want to exclude are in a common namespace there's not much I can do.

**Comment by SimonCropp** [comment]
Perhaps leverage the sequence points from the pdb?

**Comment by JakeGinnivan** [comment]
That could be dangerous because it would be different behaviour if you have pdb's vs not

**Comment by SimonCropp** [comment]
How about a diff prop. Pathregex. If it is specified and no pdb is supplied we throw a error

**Comment by JakeGinnivan** [comment]
Nah, I will just create the regex for the class names

**Comment by JakeGinnivan** [comment]
Thanks for the help, makes sense

**Comment by distantcam** [comment]
Sorry I couldn't help @JakeGinnivan. The number of times I've had ideas for Fody that involved code files and not the compiled code, I feel your pain.

**Comment by SimonCropp** [comment]
if only we had some tool that could manipulate the compiler...

**Comment by distantcam** [comment]
@SimonCropp Don't tempt me. This weekend is a long weekend.

**Comment by JakeGinnivan** [comment]
All good Cam, didn't think this issue through before posting.
