### ISSUE TITLE
Don't process nullable types

### ISSUE THREAD

**Issue by tpluscode** [Fody/NullGuard#50]
Hi

I our project a we have noticed that NullGuard processes nullable types. It is understandable, because all reference types are. However declaring parameter as `int?` implies that null value is expected.

Would you find it sensible to disable NullGuard on nullable value types altogether?

**Comment by papuashu** [comment]
Well, isn't int? a Nullable<int>, which is not null? Nullable<T> has an implicit converter to T, but Nullable<T> shouldn't be null, just parameter.Value might be null.

Therefore, a check for a Nullable<T> parameter is more than welcome and a null value is not expected. Am I right?

**Comment by ulrichb** [comment]
@tpluscode 
> I our project a we have noticed that NullGuard processes nullable types. It is understandable, because all reference types are. However declaring parameter as int? implies that null value is expected.
> 
> Would you find it sensible to disable NullGuard on nullable value types altogether?

[`Nullable<T>`](https://msdn.microsoft.com/en-us/library/b3h38hb0.aspx) is a value type and is already skipped in NullGuard (no null-check will be emitted). See the check for `IsRefType()` in the conjunction in [`MayNotBeNull()`](https://github.com/Fody/NullGuard/blob/9411f39b3e62fbfcad8dc2255858d03f02910950/Fody/CecilExtensions.cs#L81).

**Comment by tpluscode** [comment]
Oh my, did I just make a fool of myself? Don't know why I thought `Nullable<T>` was a reference type. Indeed no null check is added by NullGuard. I should actually check stuff before creating an issue ;)

**Comment by ulrichb** [comment]
np :)
