### ISSUE TITLE
Async method result rewriting doesn't work in VS 2015 (Roslyn 1.0) compiler

### ISSUE THREAD

**Issue by ulrichb** [Fody/NullGuard#56]
At the moment _NullGuard_ assumes that the compiler-generated async state machine types are structs. See [MethodProcessor.InjectMethodReturnGuardAsync()](https://github.com/Fody/NullGuard/blob/2a22688cf905e9da687fbec16eab975f223d4f7b/Fody/MethodProcessor.cs#L204).

With Roslyn 1.0 this isn't valid anymore. Roslyn generates classes instead of structs *if optimization is disabled* (i.e. by default in Debug builds) to support "Edit and Continue". See [AsyncRewriter](https://github.com/dotnet/roslyn/blob/ed79f53847606bd1bceb4fb62f2aa047e5f96b02/src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.cs#L61) and [CompilationOptions.EnableEditAndContinue](https://github.com/dotnet/roslyn/blob/0576aa0159afecb20e00fd6faa210a1f89cb2b02/src/Compilers/Core/Portable/Compilation/CompilationOptions.cs#L281).

Note: I confirmed with a local _NullGuard_ build that removing the `VariableType.IsValueType` check in `InjectMethodReturnGuardAsync` fixes this issue.

**Comment by distantcam** [comment]
Want to submit your fix as a PR?
