### ISSUE TITLE
When a non-public type implicitly implements a public interface, no null-check is generated

### ISSUE THREAD

**Issue by fschmied** [Fody/NullGuard#60]
With the default `AllPublic` validation flag, no null checks are added for implicit interface implementations on non-public types.

Example:

```
public interface IAPublicInterface
{
  void SomeMethod(string s);
}

public static class SomeFactory
{
  public static IAPublicInterface Create()
  {
    return new Implementation();
  }

  private class Implementation : IAPublicInterface
  {
    //In the current implementation, due to the private visibility of this class, no 
    //argument check will be weaved into SomeMethod, although it's visible to 
    //consumers of SomeFactory.Create()
    public void SomeMethod(string s)
    {
    }
  }
}
```

This is a remainder from #37, which fixed explicit interface implementations, but not implicit interface implementations on non-public types.

Because detecting implicit interface implementations is a very hard problem, I propose redefining the visibility check to only consider member visibility, not type visibility.

@distantcam In #37, you were positive about this change. If you still are, we could provide a pull request.

**Comment by tom-englert** [comment]
Just stepped over this. The fix in #37 is not complete:
- does not check if the implemented interface is public, explicit implementation of a non-public interface is not public!
- does not work for properties
