### ISSUE TITLE
Support Code Contracts flavor of ArgumentNullException

### ISSUE THREAD

**Issue by Deathspike** [Fody/NullGuard#63]
I stumbled upon this rather interesting weaving method, and was wondering if you could support Code Contracts flavor of output (switched on by a configuration setting)? If you aren't aware of Code Contracts, please refer to http://www.codemag.com/article/1001101 for an overview. Essentially, it is a static analyzer that supports a flavor of checking contracts (which goes well beyond just null checking), but guarding against null statements is 90% of what we use code contracts for. 

Fody runs before the Contract Contracts analyzer does its magic, so this could potentially be a very nice match to easily include additional contracts. Since NullGuard outputs only predictions and postconditions, this would be changed. Instead of:

	if (value == null)
	{
		throw new ArgumentNullException("value", "[NullGuard] Cannot set the value of property 'System.Collections.Generic.ICollection`1<Hub.Data.AccountIdentity> Hub.Data.Account::Identities()' to null.");
	}

Output the following:

	Contract.Requires(value != null, "[NullGuard] Cannot set the value of property 'System.Collections.Generic.ICollection`1<Hub.Data.AccountIdentity> Hub.Data.Account::Identities()' to null.");

And for the post-condition, an ensures needs to be added. So, with an example, instead of this:

	get
	{
		ICollection<AccountIdentity> expr_06 = this.<Identities>k__BackingField;
		if (expr_06 == null)
		{
			throw new InvalidOperationException("[NullGuard] Return value of property 'System.Collections.Generic.ICollection`1<Hub.Data.AccountIdentity> Hub.Data.Account::Identities()' is null.");
		}
		return expr_06;
	}

An ensures is added like this:

	get
	{
		Contract.Ensures(Contract.Result<ICollection<AccountIdentity>>() != null);
		ICollection<AccountIdentity> expr_06 = this.<Identities>k__BackingField;
		if (expr_06 == null)
		{
			throw new InvalidOperationException("[NullGuard] Return value of property 'System.Collections.Generic.ICollection`1<Hub.Data.AccountIdentity> Hub.Data.Account::Identities()' is null.");
		}
		return expr_06;
	}

This would make, in my opinion, Fody's NullGuard an immeasurable addition to Code Contracts.

**Comment by SimonCropp** [comment]
sorry i dont actually understand the value proposition of this. from the consumers point of view how is `throw new ArgumentNullException` different from `Contract.Requires`

**Comment by Deathspike** [comment]
The difference is that Code Contracts understands `Contract.Requires`, but doesn't understand `throw new Exception()`. When you create a class library that utilizes `NullGuard`, it generates `throw new Exception()` code. That is not a valid contract in the eyes of the Code Contracts static analyzer, and isn't documented nor exported as such. The result is that an application consuming the class library does not recognize the guarantee that the value is never null, and will show errors on the calling code saying that "*You may be performing an operation on value that may be null. Are you making assumptions the static analyzer is unaware of?*". As an example:

    // ProjectA (Class Library)
    public class SampleModel {
        private string _name;
        public SampleModel() {
            _name = "Deathspike";
        }
        public string Name {
            get {
                if (_name == null) throw new InvalidOperationException();
                return _name;
            }
            set {
                if (value == null) throw new InvalidOperationException();
                _name = value;
            }
        }
    }

    // ProjectB (Console Application)
    public class SampleProgram {
        public static void Main(string[] args) {
            var model = new SampleModel();
            Console.WriteLine(model.Name.ToUpper()); // Error. `model.Name` may be null.
        }
    }

As shown by the comment, the `model` is inferred to be not null (since you just `new`'ed it). Then we call `.ToUpper()` on `model.Name`, which has no guarantee to be non-null. This is because Code Contracts doesn't understand that the class library containing `SampleModel` ensures that the `Name` property is never null. Rewriting this to a `Contract` notation will make the static analyzer aware of the fact that `Name` is never null. This is what correct code looks like (according to the static analyzer):

    // ProjectA (Class Library)
    public class SampleModel {
        private string _name;
        public SampleModel() {
            _name = "Deathspike";
        }
        public string Name {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return _name;
            }
            set {
                Contract.Requires<ArgumentNullException>(value != null);
                _name = value;
            }
        }
    }

    // ProjectB (Console Application)
    public class SampleProgram {
        public static void Main(string[] args) {
            var model = new SampleModel();
            Console.WriteLine(model.Name.ToUpper());
        }
    }

Now the static analyzer analyzing the console application *is* aware of the contract in the class library, and correctly sees the guarantee that was made by `NullGuard` which is now understand. Now, it knows that `model` is not null, and the `Name` property guarantees that the result not null, so the `model.Name.ToUpper()` statement is analyzed by code contracts to be 100% correct and without contract violations or errors.

The reason I suggested a switch between the two different notations is to opt-in to the code contracts notation. If you don't run the code contracts rewriter, `Contract.Requires` statements (and other Contract statements) can trip up the compilation process and actually make your project unusable. Since we don't want to force anyone into using code contracts, it should be an optional switch. But, like I said, the end-result (for a code contract user) is pretty much the same, except that we have helped the static analyzer to understand our code as we intend it to be.

Hope this elaborates sufficiently. If not, I'd be happy to set up repositories illustration the issue.

**Comment by thirkcircus** [comment]
:+1: to the concept.

I used to use CodeContracts but switched to Fody.NullGuard because it's faster than the codecontracts postprocessor.

The reasoning for this issue is sound however - the value proposition for clients is that you enable them to perform static checks for potentially null arguments (passed to a nullguarded assembly).  Clients get static/compile time warnings instead of runtime exceptions...

**Comment by SimonCropp** [comment]
wouldnt it be better for code contracts to understand 

```
if (value == null)
{
    throw new ArgumentNullException("value");
}
```

**Comment by SimonCropp** [comment]
sorry but i think the scope of null guard should stay as narrow as possible. feel free to fork it and create something more comparable to code contracts
