### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by TomMarius** [Fody/NullGuard#65]
Hello,

it would be great to support .NET Core. Right now it fails saying that the type Attribute is defined in an unreferenced 'mscorlib' assembly.

**Comment by another-guy** [comment]
Referencing NullGuard.Fody doesn't break my AspNet Core project in any way. However the method parameters are not seem to be checked by NullGuard in runtime.

Please let package consumers know if there are any plans for supporting NetCore.

**Comment by 304NotModified** [comment]
I think supporting .NET Core will be difficult if Fody itself isn't supported on .NET Core :neutral_face:

**Comment by another-guy** [comment]
@304NotModified could you clarify what do you mean?

**Comment by another-guy** [comment]
@304NotModified I see. I completely forgot there's this dependency (obvious though)

**Comment by Patrickkk** [comment]
its now supported by fody https://github.com/Fody/Fody/issues/206

**Comment by 304NotModified** [comment]
yes it's supported since 2.0 (currently 2.0.7 is the latest: https://www.nuget.org/packages/Fody/2.0.7)

**Comment by Patrickkk** [comment]
@SimonCropp  Thank you for finishing this. I noticed there is no new (pre) release yet though. I don't know if this is intentional, thought I'd let you know. Ill just have to be patient :)

**Comment by SimonCropp** [comment]
this should now be on nuget
