### ISSUE TITLE
NullGuard appears to make Code Analysis complain when a manual null check is added

### ISSUE THREAD

**Issue by j2jensen** [Fody/NullGuard#66]
### Steps to reproduce
1. Create a new project (e.g. console application)
2. Set up Code Analysis on the project to use a rules file that sets [CA1062](https://msdn.microsoft.com/en-us/library/ms182182.aspx) violations as an Error-level issue.
3. Add some code that builds just fine with CA1062 enabled. For example:
   
   ```
   using System;
   
   public class Test
   {
       public void ResolveTest(object specialThing)
       {
           if (specialThing == null)
           {
               throw new ArgumentNullException(nameof(specialThing));
           }
   
           Console.WriteLine(specialThing.ToString());
       }
   }
   ```
4. Add Fody NullGuard via NuGet. 
5. Rebuild
### Results

CA1062 now complains:

> In externally visible method 'Test.ResolveTest(object)', validate parameter 'specialThing' before using it.   
### Remarks

I'm pretty baffled as to why this would be happening. As far as I can tell, using ILSpy to disassemble the compiled code, the null check looks the same with or without Fody Nullguard. But clearly something is happening to cause Visual Studio to think that the null check was removed or doesn't adequately check for nullability.

NullGuard normally does a great job of keeping CA1062 happy, but in any situation that NullGuard ignores (e.g. `[AllowNull]` attributes, or non-public classes or methods), even adding a manual null check won't appease Code Analysis.

**Comment by SimonCropp** [comment]
This looks like a bug in CA. Can u raise a bug with them
