### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by yozzozo** [Fody/NullGuard#69]
Hey guys,

.NET Standard is the future -- would be nice to support this so I can switch from using PCLs (many other packages I use are adding support, this is one of the only ones that doesn't support it).

Thanks!

**Comment by MovGP0** [comment]
starting with Visual Studio 2017, `dotnetstandard` replaces PCL, so I do not consider it the future, but the new standard. It is unfortunate that NullGuard does not support it yet.

**Comment by tomekjanicki** [comment]
Are there any plans to migrate to .net standard in the near future? As I understand now Fody (2.0.9) now supports .NET Standard 1.6.

**Comment by distantcam** [comment]
I'd happily accept a PR.

**Comment by srollinet** [comment]
Any news about these PRs?
It would be great to have that for NetStandard!
