### ISSUE TITLE
Add option to null-check `protected` members

### ISSUE THREAD

**Issue by j2jensen** [Fody/NullGuard#70]
As noted in Issue #66 NullGuard seems to cause problems with Code Analysis in `protected` methods because it doesn't add its own null checks, but it seems to affect the generated code in a way that prevents Code Analysis from recognizing manual null checks.

Since that issue has been open without any attention for some time now, I'm assuming it's probably not going to be fixable/fixed any time soon, but a good workaround would be to include an option to add null-checks to `protected` members as well as `public` ones. This would align the plugin with the expectations of Code Analysis, which considers `protected` methods to be "publicly visible" because they can be accessed by their parent class. 

It could also be a generally useful feature for developers who want null checks on more methods than just the public ones. It's reasonable to imagine that some developers would like implicit fail-fast behavior even on their private methods, for instance.

**Comment by ulrichb** [comment]
Using `[NullGuard(... | `[`ValidationFlags.NonPublic`](https://github.com/Fody/NullGuard/blob/7ad1a646ec267eab3df2933e839999ed0e6a3b2d/ReferenceAssembly/ValidationFlags.cs#L37-L40)`)]` you can enable generating checks for all non-public members (including protected). The `NullGuardAttribute` can be applied to classes or whole assemblies.

Is this sufficient for you?

**Comment by j2jensen** [comment]
Sorry it took me so long to get back to you. Yes, that NullGuard attribute looks like it'll work. Thank you so much!
