### ISSUE TITLE
Code Analysis error CA1065 when overriding ToString

### ISSUE THREAD

**Issue by DanielBretzigheimer** [Fody/NullGuard#71]
**Description**
If you override a ToString() method the visual studio shows me the warning CA1065 "Do not raise exceptions in unexpected locations" when running the code analysis (MSDN: https://msdn.microsoft.com/library/bb386039.aspx)

**Expected Behaviour**
NullGuard should at least have the option to ignore all ToString() methods.

**Current Workaround**
Setting the [return: NullGuard.AllowNull] on the ToString() resolves the warning

**Comment by ulrichb** [comment]
At the time of writing, [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring) don't say something about the return nullability of `ToString()`, but in MS Code Contracts [they define the result as not null](https://github.com/Microsoft/CodeContracts/blob/7255a95ec1de1453518852030de285d0fa001c11/Microsoft.Research/Contracts/MsCorlib/System.Object.cs#L57). I think the not-null contract should outweigh CA1065 in this case and therefore would propose to inject a SuppressMessage attribute for CA1065 instead.

**Comment by DanielBretzigheimer** [comment]
The silly thing about this is that the `ToString()` method is never null but it shows me the warning (because the exception CAN be thrown). So this means all `ToString()` methods would show this warning.

Example Code:

```
public class TestClass
{
    public string Something { get; set; } = "Something";

    public override string ToString()
    {
        return $"{this.Something}";
    }
}
```

If you run the code analysis over this code you get the warning. Even the default value for the property  does not help to hide it.

So setting the attribute would work but it would be a huge effort for us. So do you think there is the possibility about implementing a ignore for this case?

**Comment by ulrichb** [comment]
@DanielBretzigheimer I meant to add an option that _NullGuard_ injects a SuppressMessage attribute for CA1065. In my eyes this would be better than disabling the null return value check because the contract of ToString() _is_ not null (for reference see above).

**Comment by SchwabenProgger** [comment]
In my opinion, this should be changed. Even a ToString overload like that raises a CA1065 warning. There is no CA1065 warning without NullGuard.

`public override string ToString()
{
    return "Test";
}`

**Comment by SimonCropp** [comment]
yeah CA1065 is wrong. closing this
