### ISSUE TITLE
Seems to be breaking debugging info

### ISSUE THREAD

**Issue by roman-polunin-medamerica** [Fody/NullGuard#74]
Apologies if this is duplicate, because I created [https://github.com/Fody/NullGuard/issues/73](https://github.com/Fody/NullGuard/issues/73) for exactly the same reason - but that one wasn't sufficiently specific, because I assumed it would be addressed by porting to Fody 2.0.x.

Observed effect: when I apply a null guard to a method, it becomes impossible to put a breakpoint inside it. IDE shows that it won't ever be hit (and it does not hit). 

Seems like even the new version of the method CecilExtensions.HideLineFromDebugger still breaks debugging information. I looked into the latest code, and now it has `method.DebugInformation.SequencePoints.Remove(oldSequencePoint);` duplicated two times,
whereas the newly created sequencePoint is not being added anywhere.

https://github.com/Fody/NullGuard/blob/master/Fody/CecilExtensions.cs#L128

**Comment by Caleb9** [comment]
This is seriously annoying. If it's any help I'd like to add that breakpoints get hit in local methods (C# 7) as in the following code
```
    public class Program
    {
        public void HandlerMethod(object sender, EventArgs a)
        {
            /* PUT A BREAKPOINT HERE - does not get hit */
            Console.WriteLine("In HandlerMethod"); 
            LocalMethod();

            void LocalMethod()
            {
                /* PUT A BREAKPOINT HERE - does get hit */
                Console.WriteLine("In LocalMethod");
            }
        }

        private static void Main(string[] args)
        {
            var p = new Program();

            p.HandlerMethod(p, EventArgs.Empty);

            try
            {
                p.HandlerMethod(p, null);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            Console.ReadLine();
        }
    }
```
It also seems to work fine with NullGuard.Fody v1.4.6 and Fody v1.29.4 but not in v.1.5.1 and v2.0.6. Guess I'll have to downgrade until it gets fixed.

**Comment by distantcam** [comment]
Please try 1.5.2.

**Comment by roman-polunin-medamerica** [comment]
Thanks! 
The code works now for MethodProcessor and PropertyProcessor (I use a much simpler version of this attribute).

Remaining issue: the same thing needs to be done in PropertyProcessor. Without a call to UpdateDebugInfo, debugging in the property is also broken. I fixed it in my version of this code by adding the call to UpdateDebugInfo as follows: 
`                InjectPropertySetterGuard(setMethod, doc, property, valueParameter);

                setBody.InitLocals = true;
                setBody.OptimizeMacros();
                >>>> setMethod.UpdateDebugInfo(); <<<<
`

**Comment by roman-polunin-medamerica** [comment]
As a question: should there be a call to UpdateDebugInfo in the PropertyProcessor? Debugger seems to be able to step inside anyway though.

**Comment by Caleb9** [comment]
It works. Thanks!
