### ISSUE TITLE
ApprovedTests outdated?

### ISSUE THREAD

**Issue by tpluscode** [Fody/NullGuard#76]
I see that the ApprovedTests are not being executed on CI. When I run them on my box some of the fail: `ClassWithPrivateMethod`, `ClassWithPrivateMethodNoAssert` and `ErrorsList`.

I'm working on .NET Standard overhaul and unfortunately even more of those cases fail there. Would it be possible to update the failing tests on master so that the PR (coming soon) can be safely be merged?

**Comment by distantcam** [comment]
The approval tests are highly sensitive to what compiler and options are used. The tests are a decompile comparison test, and thus I don't run them on the CI.

When you run them on your box, are you using the Mono compiler? For .NET Standard I'm not sure why they're failing then.

If you have updated tests you could push them ahead of any other PRs.

**Comment by SimonCropp** [comment]
this should now be resolved
