### ISSUE TITLE
Does this work for new csproj-based projects?

### ISSUE THREAD

**Issue by cmeeren** [Fody/NullGuard#80]
I can't get this to work. I have a class library targeting .NET 4.7 using the new csproj format. I have installed `NullGuard.Fody` and my `FodyWeavers.xml` contain

```
<Weavers>
  <NullGuard IncludeDebugAssert="false" />
</Weavers>
```

The build log states that `NullGuard` is indeed running:

```
2>  Fody: Fody (version 2.1.0.0) Executing
2>    Fody/NullGuard:   	No reference to 'NullGuard.dll' found. References not modified.
2>  Fody:   Finished Fody 18ms.
```

However, when I run a unit test (in another csproj-based project) and try to pass `null` to some arguments, I get no `ArgumentNullException`. Is this because I use the new .csproj format?

**Comment by SimonCropp** [comment]
That should work. Can u upload a repro for me to have a look at

**Comment by cmeeren** [comment]
Sorry, my mistake. The class in question was `internal`. Using `[assembly: NullGuard(ValidationFlags.All)]` fixed it.

**Comment by SimonCropp** [comment]
good to hear
