### ISSUE TITLE
Jetbrains' CanBeNull doesn't work?

### ISSUE THREAD

**Issue by cmeeren** [Fody/NullGuard#81]
In my AssemblyInfo.cs, I have

```c#
[assembly: NullGuard(ValidationFlags.All)]
```

I'm using `Jetbrains.Annotations` and have a method defined (on an internal class, if that's relevant) as

```c#
public ICard Create([CanBeNull] string cardId)
```

However, when I pass null to this method, it's caught by NullGuard. What could be wrong? Do I need to configure NullGuard to accept Jetbrains' `CanBeNull` before it will work?

**Comment by cmeeren** [comment]
Here's a tiny repro solution (also relevant for #82):

[NullGuard.zip](https://github.com/Fody/NullGuard/files/1060199/NullGuard.zip)

**Comment by tom-englert** [comment]
It works as soon as you define [JETBRAINS_ANNOTATIONS](https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html) in your project
