### ISSUE TITLE
Support ItemCanBeNull

### ISSUE THREAD

**Issue by cmeeren** [Fody/NullGuard#82]
`Task<T>`-returning async methods are annotated with Resharper's `ItemCanBeNull` (not `CanBeNull`) if `T` can be null. Could you add support for `ItemCanBeNull`?

(I'm not 100% sure it doesn't already work since I can't even get `CanBeNull` to work, see #81, but your repo doesn't contain the string `ItemCanBeNull`, so I guess it's not supported.)

Here's a tiny repro solution (also posted in #81):

[NullGuard.zip](https://github.com/Fody/NullGuard/files/1060196/NullGuard.zip)

**Comment by SimonCropp** [comment]
Closing as 81 is closed
