### ISSUE TITLE
NullGuard makes R# code coverage fail

### ISSUE THREAD

**Issue by cmeeren** [Fody/NullGuard#83]
Running ReSharper's code coverage test runner fails when using NullGuard (even if `<NullGuard />` is not added to `FodyWeavers.xml` – it's sufficient that `NullGuard.Fody` is installed). The ReSharper error is:

`ERROR Coverage analysis: Inconsistent PDB detected, too large offset in statement table`

This might be related to https://github.com/vanderkleij/Smocks/pull/16, which was a very simple fix (more or less a single line).

**Comment by SimonCropp** [comment]
@cmeeren i can no longer reproduce this. i suspect it was a problem with an older version of cecil. can u update to the latest of nullguard and fody and let me know if u still have the issue?

**Comment by cmeeren** [comment]
Sorry, I don't have the time to check this for the foreseeable future. If you can't repro then it's probably fixed. Feel free to close.

**Comment by lewuaza** [comment]
I belive this is still an issue , using DotCover 2018.1.2 and Nullguard.Fody in latest version give same error

> ERROR Coverage analysis: Inconsistent PDB detected, too large offset in statement table

**Comment by tom-englert** [comment]
Looks like this could be related to #90
