### ISSUE TITLE
Returning 0 from a generic async method triggers NullGuard

### ISSUE THREAD

**Issue by j2jensen** [Fody/NullGuard#84]
Here's a simplified version of the situation where I noticed this happening:

```
public async Task<T> GetThing(Func<T> getThing)
{
    return getThing();
}
```
```
GetThing(() => 0);
```

I'm guessing this happens because you can't compare the generic return value to `null`, since it may not be an object. So the generated code is probably comparing to `default(T)`, but for struct types `default(T)` is not null, and is typically a perfectly legitimate value.

**Comment by SimonCropp** [comment]
Can u submit a pr that fixes this

**Comment by ulrichb** [comment]
Close? For a non-fixed bug report?

**Comment by SimonCropp** [comment]
ok will leave it open for a while to see if someone wants to fix it

**Comment by SimonCropp** [comment]
seems not

**Comment by SimonCropp** [comment]
if someone wants this fixed please submit a PR

**Comment by ulrichb** [comment]
Sorry, but I really see no benefit in closing non-fixed bugs.

**Comment by tom-englert** [comment]
I'll take care of this

**Comment by SimonCropp** [comment]
Want me to deploy this?

**Comment by tom-englert** [comment]
@SimonCropp yes, maybe #90 will take some more time to fix, so making this fix available now is a good idea.
