### ISSUE TITLE
NuGet failed with .NET 4.5.2

### ISSUE THREAD

**Issue by maxbgn** [Fody/NullGuard#87]
I've tried to add NullGuard.Fody to project, but got an error:

> Install failed. Rolling back...
> Could not install package 'NullGuard.Fody 1.6.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I've installed version 1.5.2 manually via console, and it works fine. Looks like the issue is with the latest version only.

**Comment by SimonCropp** [comment]
What version of nuget?

**Comment by maxbgn** [comment]
2.8.60318

**Comment by SimonCropp** [comment]
that is a bug in older versions of nuget. u need to update

**Comment by maxbgn** [comment]
Ok, thanks for your help.
