### ISSUE TITLE
Can't open the project in VS2015

### ISSUE THREAD

**Issue by MrYossu** [Fody/NullGuard#91]
Hello,

I wanted to take a look at the source code, but when I open the solution in VS2015, none of the projects load. If I right-click on one and try to load in manually, I get the following error...

![image](https://user-images.githubusercontent.com/10185332/32745813-c98db8a6-c8ab-11e7-9522-c8fd7a6fba00.png)

I tried adding the suggested code to the <project> element, but it didn't make any difference.

How do I open the projects in VS?

Thanks

**Comment by SimonCropp** [comment]
You need VS2017

**Comment by MrYossu** [comment]
Great! Thanks for the fast response.
