### ISSUE TITLE
Can we add NullGuard to selected classes only?

### ISSUE THREAD

**Issue by MrYossu** [Fody/NullGuard#92]
Hello,

We have a fairly mature application that contains loads of classes. We would like to introduce NullGuard, but can't do this to every class at once, as it would require too much refactoring in one go.

Ideally, we would like to add NullGuard, but be able to choose which classes it was used on. That way, we could introduce it in stages, giving us time to check each class's API to see can be marked as nullable, and test it all.

Can we do this? Thanks

**Comment by tpluscode** [comment]
I haven't tried myself yet but I think you should use [explicit mode](../#explicit-mode) and manually setting a `[NotNull]` attribute where applicable

**Comment by MrYossu** [comment]
Thanks for the reply, but that opt-in approach is largely what I want to avoid. I guess I'm trying to have my cake and eat it, as I want the NullGuard approach to be the default (so developers are forced to make a conscious decision to disable it), but don't want to have to modify every class before we start.

I guess we'll have to come down one way or the other.

**Comment by SimonCropp** [comment]
it seems u are asking for two things that conflict each other

**Comment by MrYossu** [comment]
possibly, but was worth asking anyway. I'm faced with a tough decision on how to add this to our project. I want to end up in a situation where it's the default, and a developer has to make a conscious decision to disable it, but don't want to jump in and make it the default in one go, due to the immense implications of code change that this would involve.

I guess you're right, the two aims do contradict. What would you suggest? Thanks

**Comment by SimonCropp** [comment]
Sorry i dont know what to suggest. 

But if u come up with any ideas perhaps submit a pr with tests that show how you think it should work
