### ISSUE TITLE
Nuget still have 1.6.2 version

### ISSUE THREAD

**Issue by GraySerg** [Fody/NullGuard#94]
But information at main page describes 1.6.3 version.
Is it possible to update nuget package?

**Comment by tom-englert** [comment]
@SimonCropp I think I can't publish releases, will you create one? Code should be fine.

**Comment by SimonCropp** [comment]
ok i pushed 1.6.3

@tom-englert  "adds new major features" does not mean a major bump. since we follow semver, only a breaking change would require a major version number change

**Comment by tom-englert** [comment]
:+1:
