### ISSUE TITLE
.net core 1.0 - Msbuild compilation fails

### ISSUE THREAD

**Issue by sumit4palz** [Fody/NullGuard#96]
I am trying to use Fody Nullguard in net Core 1.0 class library project.  Currently using v 1.6.3 for Nullguard.Fody.  

While compiling the project using MSBuild I am getting following error.  Is this a known issue?

C:\Users\<username>\.nuget\packages\fody\2.2.1\build\netstandard1.2\Fody.target
s(90,5): error MSB4062: **The "Fody.VerifyTask" task could not be loaded from the
assembly** C:\Users\sumit.gupta\.nuget\packages\fody\2.2.1\build\netstandard1.2\..
\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system c
annot find the file specified. Confirm that the <UsingTask> declaration is corre
ct, that the assembly and all its dependencies are available, and that the task
contains a public class that implements Microsoft.Build.Framework.ITask

**Comment by SimonCropp** [comment]
Do other msbuild tasks work?

**Comment by sumit4palz** [comment]
Haven't tried anything else other than release or debug build.
