### ISSUE TITLE
NullGuard does not add an entry into FodyWeavers.xml

### ISSUE THREAD

**Issue by tom-englert** [Fody/NullGuard#98]
Even though this does no longer work for .netstandard projects, it should still work for old-style .net45 projects like all other weavers, too.

**Comment by SimonCropp** [comment]
True but it has always had bugs that cannot be fixed. Eg if u update two weavers in the same nuget operation it will corrupt the xml. And it is  better to teach people to own it and have it be consistent. I am in the process of removing the auto add behaviour from all other weavers

**Comment by tom-englert** [comment]
I see, should I revert this last commit?

**Comment by SimonCropp** [comment]
i think yes

**Comment by tom-englert** [comment]
OK, reverted

**Comment by tom-englert** [comment]
@SimonCropp Since the future is to manually manage the FodyWeavers.xml, I did a quick prototype to manage weaver configuration across all projects in a solution.

The first version is read-only, just giving an overview of what is configured:

http://vsixgallery.com/extension/e31595c9-3e0c-4f5c-b35c-dd8d61e364d1/

What do you think about this approach?

**Comment by SimonCropp** [comment]
is that the correct url?

**Comment by tom-englert** [comment]
Yes, since that also deals with kind of project configuration I just added it as a new feature there, so I did not have to reinvent the infrastructure.
