### ISSUE TITLE
AutodetectMode not setting Explicit for [NotNull] on classes

### ISSUE THREAD

**Issue by ldwedari** [Fody/NullGuard#99]
The ExplicitMode.AutodetectMode() extension method does not set the mode to Explicit if the NotNullAttribute is applied only at class level. Other levels (method, parameter and property) are working fine.
As you can see the following code does nothing to check if a type is decorated:
```
        foreach (var typeDefinition in moduleDefinition.GetTypes())
        {
            foreach (var method in typeDefinition.Methods)
            {
                if (method.GetNullabilityAttributes().HasFlag(NullabilityAttributes.NotNull) || method.Parameters.Any(parameter => parameter.GetNullabilityAttributes().HasFlag(NullabilityAttributes.NotNull)))
                {
                    return NullGuardMode.Explicit;
                }
            }

            if (typeDefinition.Properties.Any(property => property.GetNullabilityAttributes().HasFlag(NullabilityAttributes.NotNull)))
            {
                return NullGuardMode.Explicit;
            }
        }
```
The following line should be added:
```            
if (typeDefinition.GetNullabilityAttributes().HasFlag(NullabilityAttributes.NotNull))
    return NullGuardMode.Explicit;
```

**Comment by tom-englert** [comment]
@ldwedari: what is the means of `NotNull` on class level? Does R# recognize this?

**Comment by tom-englert** [comment]
@SimonCropp I have already added a fix for constructors (#97), but is has never been released.

**Comment by ldwedari** [comment]
@tom-englert: it seems that Resharper indeed does not do anything (at least to me) when annotating a type.

I would expect `NullGuard` to behave like `Postsharp` `NotNull`. That is multicasting the aspect to all elements of the class. The problem is Resharper does not have the concept of AOP. So it does not multicast. So adding `NotNull` or `CanBeNull` to a class will not tell Resharper to check the null references on the methods.

I've also tried my own `NotNull` attribute instead the one in `JetBrains.Annotations`. The result is still the same: no multicast of the aspect.

I understand that it is better to use implicit mode. But sometimes explicit is needed when adding NullGuard to an existing project and you want to convince your colleagues how useful it is. Forcing you to add `NotNull` in every single place is not helping with that. In my opinion, NullGuard should introduce its own NotNull attribute that indicates to multicast.

At the moment, the only solution I see is to use implicit mode, apply `NullGuard(ValidationFlags.None)` at assembly level and `NullGuard(ValidationFlags.AllPublic)` at the classes where I what not null to be applied globally.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
